#cloud-config

write_files:
    - path: /usr/local/bin/createSSHCertAuth.sh
      content: | 
          #!/bin/bash
          echo -e "\n\n\n" | ssh-keygen -f ~/.ssh/ssh_CA  -N ""
          echo -e "\n\n\n" | ssh-keygen -t ed25519 -C "FOR IA ACCESS ONLY" -N ""
          ssh-keygen -s ~/.ssh/ssh_CA -I adam_dost -n IA_Auditor -V +1d ~/.ssh/id_ed25519.pub
          umask 700
          mkdir /home/cceaudadmin/
          mkdir /home/cceaudadmin/.ssh
          touch /home/cceaudadmin/.ssh/authorized_keys
          echo -n "cert-authority " >> /home/cceaudadmin/authorized_keys
          cat ~/.ssh/ssh_CA >> /home/cceaudadmin/authorized_keys    

runcmd:
    - sudo chmod u+x /usr/local/bin/createSSHCertAuth.sh
    - sudo bash /usr/local/bin/createSSHCertAuth.sh
    - sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    - sudo sh -c 'echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo'
    - sudo yum install azure-cli
    - sudo curl https://packages.microsoft.com/config/rhel/7/prod.repo | sudo tee /etc/yum.repos.d/microsoft.repo
ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8Qt2J/F+/I4b5Pj1o5xbiqjJay+qG+lj7s0Mx4xifa1mFz2JXjBihFcnwI5LAX6kqdHwIjzyDPiZ//wvd9hTRBE/F3JPZSEfOjq1HD189cuHIcmJjbnqp1VwsDizO7PZ15JmqISNb85HhNN35JlJK578wMUWcQcNwjlGFs2HCwaCvhBkZuty9x0eIejqmxJF+YEVACyf/ltyL30tD2qcFaUaLljgvnP2sePQF/UqWwmW0NCRQTlRYFzHYbt2vPq36/dQIa8VHuIMkCRRdoAIJL0Meg73UFUy5zkbsV2qU20IgoKCiHmM0WF5rzr/8knAwWR+o/lMtr+OEag0YEoaP imported-openssh-key
    #This is my key feel free to change this to yours

yum_repos:
    packages-microsoft-com-prod:
        baseurl: https://packages.microsoft.com/rhel/7/prod/
        name: packages-microsoft-com-prod
        enabled: true

package_update: true
